name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  webhook:
    name: Ping webhook
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Use curl to ping each webhook
        env:
          DEPLOY_WEBHOOK: ${{ secrets.DEPLOY_WEBHOOK }}
        run: |
          echo "$DEPLOY_WEBHOOK" | while read -r url; do
            # Skip empty lines and comments
            if [ -n "$url" ] && [ "${url:0:1}" != "#" ]; then
              curl -n "$url"
            fi
          done
